### PR TITLE
fix(ModalWindow.svelte): Size to 100% on small displays

### LINKED ISSUE #827: Improve sizing of Release planner popup for smaller displays
When only on half the screen (or on phone), the release planner pop up looks like this:

Image

I think it makes more sense to extend the popup to not have that big margin/padding on smaller widths. It is unnecessary small right now

### PR DESCRIPTION
**Pull request by k0machi**
This fixes an issue where modal windows would still be trying to size
themselves to 50 or 75% of the screen even if it was too small.

Since ModalWindow is not used everywhere this doesn't affect all modal
windows present in Argus, but it should affect most of them.

Closes #828
Fixes #827

### CODE REVIEW

**Comment by k0machi** [comment]
Large-ish display:

image

Small-ish display:

image

File: frontend/Common/ModalWindow.svelte [hunk 1]
```diff
@@ -19,10 +20,10 @@
     }
 </script>
 
-<svelte:window onkeydown={handleKeyDown} />
+<svelte:window onkeydown={handleKeyDown} bind:innerWidth={innerWidth} />
 <div class="modal-window">
     <div class="d-flex align-items-center justify-content-center p-4">
-        <div class="rounded bg-white p-4 {widthClass}">
+        <div class="rounded bg-white p-4 {innerWidth >= 768 ? widthClass : "w-100"}">
```
Comment (pehala) [inline frontend/Common/ModalWindow.svelte]: why not use [bootstrap](https://getbootstrap.com/docs/5.3/layout/containers/) containers?

Comment (pehala) [reply frontend/Common/ModalWindow.svelte]: ok, lets keep it as is
